export const INCREMENT_BREAK = "INCREMENT_BREAK";
export const DECREMENT_BREAK = "DECREMENT_BREAK";
export const INCREMENT_SESSION = "INCREMENT_SESSION";
export const DECREMENT_SESSION = "DECREMENT_SESSION";
export const RESET = "RESET";
export const DECREMENT_TIME_LEFT = "DECREMENT_TIME_LEFT";
export const PLAY_PAUSE_CLOCK = "PLAY_PAUSE_CLOCK";
export const CHANGE_ACTIVE_SESSION = "CHANGE_ACTIVE_SESSION";
